Repository coding-union-kr/siltarae-be, pull requests merged in 2024-02, with the labels that each got.

#189 refactor: [#188] 액세스 토큰 재발급 로직 수정
  src/main/java/weavers/siltarae/login/domain/TokenProvider.java
  src/main/java/weavers/siltarae/login/service/LoginService.java
Labels: 🔨Refactor

#187 refactor: [#168] 태그에 속한 실수 개수 카운트 시, 삭제된 실수 필터링 추가
  src/main/java/weavers/siltarae/global/image/domain/Image.java
  src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
  src/main/java/weavers/siltarae/tag/dto/response/TagListResponse.java
  src/main/java/weavers/siltarae/tag/dto/response/TagResponse.java
  src/main/java/weavers/siltarae/tag/service/TagService.java
Labels: 🔨Refactor

#192 refactor: [#191] 리다이렉트 URI를 프론트에서 받아오도록 수정
  src/main/java/weavers/siltarae/login/controller/LoginController.java
  src/main/java/weavers/siltarae/login/domain/GoogleProvider.java
  src/main/java/weavers/siltarae/login/domain/OAuthProvider.java
  src/main/java/weavers/siltarae/login/dto/request/LoginRequest.java
  src/main/java/weavers/siltarae/login/service/LoginService.java
Labels: 🔨Refactor

#193 deploy: 백엔드 배포
  build.gradle
  src/main/java/weavers/siltarae/global/image/domain/Image.java
  src/main/java/weavers/siltarae/login/controller/LoginController.java
  src/main/java/weavers/siltarae/login/domain/GoogleProvider.java
  src/main/java/weavers/siltarae/login/domain/OAuthProvider.java
  src/main/java/weavers/siltarae/login/domain/TokenProvider.java
  src/main/java/weavers/siltarae/login/dto/request/LoginRequest.java
  src/main/java/weavers/siltarae/login/service/LoginService.java
  src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
  src/main/java/weavers/siltarae/tag/dto/response/TagListResponse.java
  src/main/java/weavers/siltarae/tag/dto/response/TagResponse.java
  src/main/java/weavers/siltarae/tag/service/TagService.java
Labels: 🌏 Deploy

#195 refactor: [#194] 로그인 성공 시, 토큰 정보와 회원 정보를 함께 반환하도록 수정
  src/main/java/weavers/siltarae/login/AuthArgumentResolver.java
  src/main/java/weavers/siltarae/login/controller/LoginController.java
  src/main/java/weavers/siltarae/login/domain/LoginInfo.java
  src/main/java/weavers/siltarae/login/domain/TokenPair.java
  src/main/java/weavers/siltarae/login/dto/response/LoginResponse.java
  src/main/java/weavers/siltarae/login/infrastructure/GoogleAuthClient.java
  src/main/java/weavers/siltarae/login/infrastructure/GoogleProvider.java
  src/main/java/weavers/siltarae/login/infrastructure/OAuthProvider.java
  src/main/java/weavers/siltarae/login/infrastructure/TokenProvider.java
  src/main/java/weavers/siltarae/login/service/LoginService.java
  src/main/java/weavers/siltarae/member/service/MemberService.java
  src/test/java/weavers/siltarae/global/ControllerTest.java
  src/test/java/weavers/siltarae/integration/BaseIntegrationTest.java
Labels: 🔨Refactor

#196 deploy: 백엔드 재배포
  src/main/java/weavers/siltarae/login/AuthArgumentResolver.java
  src/main/java/weavers/siltarae/login/controller/LoginController.java
  src/main/java/weavers/siltarae/login/domain/LoginInfo.java
  src/main/java/weavers/siltarae/login/domain/TokenPair.java
  src/main/java/weavers/siltarae/login/dto/response/LoginResponse.java
  src/main/java/weavers/siltarae/login/infrastructure/GoogleAuthClient.java
  src/main/java/weavers/siltarae/login/infrastructure/GoogleProvider.java
  src/main/java/weavers/siltarae/login/infrastructure/OAuthProvider.java
  src/main/java/weavers/siltarae/login/infrastructure/TokenProvider.java
  src/main/java/weavers/siltarae/login/service/LoginService.java
  src/main/java/weavers/siltarae/member/service/MemberService.java
  src/test/java/weavers/siltarae/global/ControllerTest.java
  src/test/java/weavers/siltarae/integration/BaseIntegrationTest.java
Labels: 🌏 Deploy

#198 fix: [#197] 로그아웃 시 리프레시 토큰 쿠키 삭제 로직 추가
  src/main/java/weavers/siltarae/login/controller/LoginController.java
Labels: 🐞 Bug

#200 fix: [#199] 태그명 중복 검사 조건 수정
  src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
  src/main/java/weavers/siltarae/tag/service/TagService.java
  src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
Labels: 🐞 Bug

#202 fix: 댓글 등록 Response 에 memberImageUrl 추가
  src/main/java/weavers/siltarae/comment/service/CommentService.java
Labels: 🐞 Bug

#203 deploy: 백엔드 버그 수정 내역 배포
  src/main/java/weavers/siltarae/comment/service/CommentService.java
  src/main/java/weavers/siltarae/login/controller/LoginController.java
  src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
  src/main/java/weavers/siltarae/tag/service/TagService.java
  src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
Labels: 🌏 Deploy
