Repository coding-union-kr/siltarae-be, pull requests merged in 2024-01, with the labels that each got.

#144 fix: [#141] 생성자에서 Tag.mistakes 필드 초기화
  src/main/java/weavers/siltarae/tag/domain/Tag.java
Labels: 🐞 Bug

#145 Deploy: 설정파일 수정 & 오류 수정 배포
  src/main/java/weavers/siltarae/tag/domain/Tag.java
Labels: 🌏 Deploy

#149 feat: [#147] 프로필 이미지 삭제 API 추가
  src/main/java/weavers/siltarae/member/controller/MemberController.java
  src/main/java/weavers/siltarae/member/dto/response/MemberImageResponse.java
  src/main/java/weavers/siltarae/member/service/MemberService.java
Labels: ✨ Feature

#151 refactor: [#137] 댓글 등록 시 등록된 댓글 Response 추가
  src/main/java/weavers/siltarae/comment/controller/CommentController.java
  src/main/java/weavers/siltarae/comment/service/CommentService.java
Labels: 🔨Refactor

#150 refactor: [#148] 프로필 이미지 관련 기능 리팩토링
  src/main/java/weavers/siltarae/global/image/ImageUtil.java
  src/main/java/weavers/siltarae/global/image/domain/Image.java
  src/main/java/weavers/siltarae/member/controller/MemberController.java
  src/main/java/weavers/siltarae/member/domain/Member.java
  src/main/java/weavers/siltarae/member/service/MemberService.java
Labels: 🔨Refactor

#153 test: [#146] 닉네임 수정 관련 테스트 추가
  build.gradle
  src/main/java/weavers/siltarae/member/controller/MemberController.java
  src/main/java/weavers/siltarae/member/service/MemberService.java
  src/test/java/weavers/siltarae/global/ControllerTest.java
  src/test/java/weavers/siltarae/integration/BaseIntegrationTest.java
  src/test/java/weavers/siltarae/integration/member/MemberIntegrationTest.java
  src/test/java/weavers/siltarae/member/controller/MemberControllerTest.java
  src/test/java/weavers/siltarae/tag/TagTestFixture.java
  src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
Labels: ✅Test

#155 refactor: [#139] Test 유저 가져오는 것 실제 Member 로 변경
  src/main/java/weavers/siltarae/comment/domain/repository/CommentRepository.java
  src/main/java/weavers/siltarae/comment/service/CommentService.java
  src/main/java/weavers/siltarae/like/service/LikeService.java
  src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
  src/main/java/weavers/siltarae/mistake/service/MistakeService.java
Labels: 🔨Refactor

#157 fix: [#138] 실수와 피드 목록에서 삭제된 댓글도 카운팅 되서 반환되는 것 수정
  src/main/java/weavers/siltarae/mistake/controller/FeedController.java
  src/main/java/weavers/siltarae/mistake/domain/Mistake.java
  src/main/java/weavers/siltarae/mistake/dto/response/FeedListResponse.java
  src/main/java/weavers/siltarae/mistake/dto/response/FeedResponse.java
  src/main/java/weavers/siltarae/mistake/dto/response/MistakeResponse.java
Labels: 🐞 Bug

#159 refactor: [#158] https://localhost 요청 허용
  src/main/java/weavers/siltarae/global/config/CorsConfig.java
Labels: 🔨Refactor

#160 Deploy: 설정파일 수정 및 이슈 사항 배포
  build.gradle
  src/main/java/weavers/siltarae/comment/controller/CommentController.java
  src/main/java/weavers/siltarae/comment/domain/repository/CommentRepository.java
  src/main/java/weavers/siltarae/comment/service/CommentService.java
  src/main/java/weavers/siltarae/global/config/CorsConfig.java
  src/main/java/weavers/siltarae/global/image/ImageUtil.java
  src/main/java/weavers/siltarae/global/image/domain/Image.java
  src/main/java/weavers/siltarae/like/service/LikeService.java
  src/main/java/weavers/siltarae/member/controller/MemberController.java
  src/main/java/weavers/siltarae/member/domain/Member.java
  src/main/java/weavers/siltarae/member/dto/response/MemberImageResponse.java
  src/main/java/weavers/siltarae/member/service/MemberService.java
  src/main/java/weavers/siltarae/mistake/controller/FeedController.java
  src/main/java/weavers/siltarae/mistake/domain/Mistake.java
  src/main/java/weavers/siltarae/mistake/domain/repository/MistakeRepository.java
  src/main/java/weavers/siltarae/mistake/dto/response/FeedListResponse.java
  src/main/java/weavers/siltarae/mistake/dto/response/FeedResponse.java
  src/main/java/weavers/siltarae/mistake/dto/response/MistakeResponse.java
  src/main/java/weavers/siltarae/mistake/service/MistakeService.java
  src/test/java/weavers/siltarae/global/ControllerTest.java
  src/test/java/weavers/siltarae/integration/BaseIntegrationTest.java
  src/test/java/weavers/siltarae/integration/member/MemberIntegrationTest.java
  src/test/java/weavers/siltarae/member/controller/MemberControllerTest.java
  src/test/java/weavers/siltarae/tag/TagTestFixture.java
  src/test/java/weavers/siltarae/tag/service/TagServiceTest.java
Labels: 🌏 Deploy

#140 feat: [#122] 암호화 복호화 구현
  src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
  src/main/java/weavers/siltarae/global/util/CryptoUtil.java
  src/main/java/weavers/siltarae/member/domain/Member.java
Labels: ✨ Feature

#162 refactor: getMistakeList() 메서드 개선
  src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
  src/main/java/weavers/siltarae/mistake/controller/FeedController.java
  src/main/java/weavers/siltarae/mistake/service/FeedService.java
  src/main/java/weavers/siltarae/mistake/service/MistakeService.java
  src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
Labels: 🔨Refactor

#165 feat: [#163] @Auth 어노테이션 필수여부 속성 및 관련 로직 추가
  src/main/java/weavers/siltarae/login/AccessTokenExtractor.java
  src/main/java/weavers/siltarae/login/Auth.java
  src/main/java/weavers/siltarae/login/AuthArgumentResolver.java
Labels: ✨ Feature

#171 refactor: [#169] 댓글목록 및 피드목록 Response 에 회원의 이미지 정보 추가
  src/main/java/weavers/siltarae/comment/dto/response/CommentResponse.java
  src/main/java/weavers/siltarae/mistake/dto/response/FeedResponse.java
Labels: 🔨Refactor

#173 fix: [#172] 복합키 키 클래스에 직렬화 기능 추가
  src/main/java/weavers/siltarae/like/domain/LikeId.java
Labels: 🐞 Bug

#175 fix: 현재 사용하지 않는 QueryDsl 설정 수정
  build.gradle
Labels: 🐞 Bug

#176 Deploy: 3차 스프린트 완료 및 4차 스프린트 일부 배포 및 오류 수정
  build.gradle
  src/main/java/weavers/siltarae/comment/dto/response/CommentResponse.java
  src/main/java/weavers/siltarae/global/exception/ExceptionCode.java
  src/main/java/weavers/siltarae/global/util/CryptoUtil.java
  src/main/java/weavers/siltarae/like/domain/LikeId.java
  src/main/java/weavers/siltarae/like/domain/repository/LikeRepository.java
  src/main/java/weavers/siltarae/login/AccessTokenExtractor.java
  src/main/java/weavers/siltarae/login/Auth.java
  src/main/java/weavers/siltarae/login/AuthArgumentResolver.java
  src/main/java/weavers/siltarae/member/domain/Member.java
  src/main/java/weavers/siltarae/mistake/controller/FeedController.java
  src/main/java/weavers/siltarae/mistake/dto/response/FeedListResponse.java
  src/main/java/weavers/siltarae/mistake/dto/response/FeedResponse.java
  src/main/java/weavers/siltarae/mistake/dto/response/MistakeListResponse.java
  src/main/java/weavers/siltarae/mistake/dto/response/MistakeResponse.java
  src/main/java/weavers/siltarae/mistake/service/FeedService.java
  src/main/java/weavers/siltarae/mistake/service/MistakeService.java
  src/main/java/weavers/siltarae/tag/domain/repository/TagRepository.java
  src/test/java/weavers/siltarae/integration/member/MemberIntegrationTest.java
Labels: 🌏 Deploy

#179 docs: [#170] 리드미 작성하기
  README.md
Labels: 📝 Docs

#180 refactor: [#178] 다대다 연관관계 테이블 복합키 순서 변경
  src/main/java/weavers/siltarae/mistake/domain/Mistake.java
  src/main/java/weavers/siltarae/tag/domain/Tag.java
Labels: 🔨Refactor

#181 deploy: 실타래 CI/CD 자동화 및 배포 방법 수정
  .github/workflows/CD.yml
Labels: 🌏 Deploy

#182 docs: [#170] 리드미 수정
  README.md
Labels: 📝 Docs

#184 deploy: [#177] 배포 시 if(main) 조건 추가
  .github/workflows/CD.yml
Labels: 🌏 Deploy

#183 Deploy: 배포자동화, 연관관계 테이블 명 수정 배포
  .github/workflows/CD.yml
  README.md
  src/main/java/weavers/siltarae/mistake/domain/Mistake.java
  src/main/java/weavers/siltarae/tag/domain/Tag.java
Labels: 🌏 Deploy

#186 setting: [#185] S3 관련 패키지 변경
  build.gradle
Labels: ⚙️Setting
